name: Release

on:
  workflow_run:
    workflows: ["Generate Changelog"] # Ждём завершения другого workflow
    types: [completed]
  push:
    branches: [master]
    tags: ['v*'] # Триггер на теги вида v1.0.0

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get release notes from CHANGELOG.md
        id: changelog
        run: |
          RELEASE_NOTES=$(awk '/^## / {if(++n == 2) exit} n' CHANGELOG.md | sed '1d')
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.release_notes }}
          draft: false
          prerelease: false
